In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('../data/processed/cleaned_bank_data.csv')

df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
df['AgeGroup'] = pd.cut(
    df['Age'],
    bins=[0, 29, 45, 60, 100],
    labels=['<30', '30-45', '46-60', '60+']
)

df['AgeGroup'].value_counts()

AgeGroup
30-45    6248
46-60    1647
<30      1641
60+       464
Name: count, dtype: int64

In [7]:
df['CreditScoreBand'] = pd.cut(
    df['CreditScore'],
    bins=[0, 599, 749, 900],
    labels=['Low', 'Medium', 'High']
)

df['CreditScoreBand'].value_counts()

CreditScoreBand
Medium    5343
Low       3034
High      1623
Name: count, dtype: int64

In [8]:
df['TenureGroup'] = pd.cut(
    df['Tenure'],
    bins=[-1, 2, 7, 10],
    labels=['New', 'Mid-Term', 'Long-Term']
)

df['TenureGroup'].value_counts()

TenureGroup
Mid-Term     5005
Long-Term    2499
New          2496
Name: count, dtype: int64

In [9]:
def balance_segment(balance):

    if balance == 0:
        return 'Zero Balance'

    elif balance < 100000:
        return 'Low Balance'

    else:
        return 'High Balance'


df['BalanceSegment'] = df['Balance'].apply(balance_segment)

df['BalanceSegment'].value_counts()

BalanceSegment
High Balance    4799
Zero Balance    3617
Low Balance     1584
Name: count, dtype: int64

In [10]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,AgeGroup,CreditScoreBand,TenureGroup,BalanceSegment
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1,30-45,Medium,New,Zero Balance
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,30-45,Medium,New,Low Balance
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,30-45,Low,Long-Term,High Balance
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,30-45,Medium,New,Zero Balance
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,30-45,High,New,High Balance

In [11]:
df.to_csv(
    '../data/processed/segmented_bank_data.csv',
    index=False
)

print("Segmented dataset saved successfully!")

Segmented dataset saved successfully!

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  str
 2   Gender           10000 non-null  str
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
 11  AgeGroup         10000 non-null  category
 12  CreditScoreBand  10000 non-null  category
 13  TenureGroup      10000 non-null  category
 14  BalanceSegment   10000 non-null  str
dtypes: category(3), float64(2), int64(7), str(3)
memory usage: 1.2 MB

In [ ]:
df[['AgeGroup',
    'CreditScoreBand',
    'TenureGroup',
    'BalanceSegment']].head()

  AgeGroup CreditScoreBand TenureGroup BalanceSegment
0    30-45          Medium         New   Zero Balance
1    30-45          Medium         New    Low Balance
2    30-45             Low   Long-Term   High Balance
3    30-45          Medium         New   Zero Balance
4    30-45            High         New   High Balance

:

In [3]:
print("Age Groups")
print(df['AgeGroup'].value_counts())

print("\nCredit Score Bands")
print(df['CreditScoreBand'].value_counts())

print("\nTenure Groups")
print(df['TenureGroup'].value_counts())

print("\nBalance Segments")
print(df['BalanceSegment'].value_counts())

Age Groups
AgeGroup
30-45    6248
46-60    1647
<30      1641
60+       464
Name: count, dtype: int64

Credit Score Bands
CreditScoreBand
Medium    5343
Low       3034
High      1623
Name: count, dtype: int64

Tenure Groups
TenureGroup
Mid-Term     5005
Long-Term    2499
New          2496
Name: count, dtype: int64

Balance Segments
BalanceSegment
High Balance    4799
Zero Balance    3617
Low Balance     1584
Name: count, dtype: int64

In [4]:
churn_rate = df['Exited'].mean() * 100

print(f"Overall Churn Rate: {churn_rate:.2f}%")

Overall Churn Rate: 20.37%

In [5]:
summary = pd.DataFrame({
    "Metric": [
        "Total Customers",
        "Churned Customers",
        "Retained Customers",
        "Churn Rate (%)"
    ],
    "Value": [
        len(df),
        df['Exited'].sum(),
        len(df)-df['Exited'].sum(),
        round(df['Exited'].mean()*100, 2)
    ]
})

summary

               Metric     Value
0     Total Customers  10000.00
1   Churned Customers   2037.00
2  Retained Customers   7963.00
3      Churn Rate (%)     20.37